Update 101-compile

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,2 +1,14 @@
 #!/bin/bash
-python3 -m compileall -b $PYFILE i
+
+pyfile=$PYFILE
+
+if [ -z "$pyfile" ]; then
+  echo "Error: PYFILE environment variable not set"
+else
+  python -m py_compile "$pyfile"
+  if [ $? -eq 0 ]; then
+    echo "Compiled $pyfile to ${pyfile}c"
+  else
+    echo "Error compiling $pyfile"
+  fi
+fi
